// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEtyO4A20It8ZTiTt6Yu5b37HxGQUsdhI',
    appId: '1:380760154922:web:dd6624f953cece62e9b453',
    messagingSenderId: '380760154922',
    projectId: 'registrationapp-1b9f2',
    authDomain: 'registrationapp-1b9f2.firebaseapp.com',
    storageBucket: 'registrationapp-1b9f2.appspot.com',
    measurementId: 'G-FT37V5CZ89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA4kH_YnZXvE8UVhZw9q1ORLByR87y62o',
    appId: '1:380760154922:android:6144776c3a4a6a2fe9b453',
    messagingSenderId: '380760154922',
    projectId: 'registrationapp-1b9f2',
    storageBucket: 'registrationapp-1b9f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6BB0nM5cJxRTLV9PxYV3RmRKjo3SZbY4',
    appId: '1:380760154922:ios:c6cbdbe326331120e9b453',
    messagingSenderId: '380760154922',
    projectId: 'registrationapp-1b9f2',
    storageBucket: 'registrationapp-1b9f2.appspot.com',
    iosBundleId: 'com.example.registrastionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6BB0nM5cJxRTLV9PxYV3RmRKjo3SZbY4',
    appId: '1:380760154922:ios:c73493ccd2476ebfe9b453',
    messagingSenderId: '380760154922',
    projectId: 'registrationapp-1b9f2',
    storageBucket: 'registrationapp-1b9f2.appspot.com',
    iosBundleId: 'com.example.registrastionapp.RunnerTests',
  );
}
